# Generated by Django 2.1 on 2018-08-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('isadmin', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=40)),
                ('middlename', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
