# Generated by Django 2.1 on 2018-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180816_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='examschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('dt', models.DateField()),
                ('frm', models.CharField(max_length=40)),
                ('to', models.CharField(max_length=40)),
            ],
        ),
    ]
