# Generated by Django 2.1 on 2018-08-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_examschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='examschedule',
        ),
    ]
