# Generated by Django 2.1 on 2018-08-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('deptname', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department'),
        ),
    ]
