# Generated by Django 2.1 on 2018-08-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_remove_parent_unm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='age',
        ),
    ]
