# Generated by Django 2.1 on 2018-08-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0002_auto_20180816_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.department'),
        ),
    ]
