# Generated by Django 2.1 on 2018-08-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subjectid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(max_length=40)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
